builds:
  - dir: .
    goos: [linux]
    goarch: [amd64]
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^Merge pull request'
